#!/usr/bin/env fish
source /home/remco-stoeten/.config/dotfiles/aliases/init.fish

# Source all .fish files in the current directory
#for file in (dirname (status --current-filename))/*.fish
#  if test (basename $file) != (basename (status --current-filename))
#  source $file
#end
#end

## Source all .fish files in the aliases directory
#for file in (dirname (status --current-filename))/aliases/*.fish
#   source $file
#end

#source './aliases/dev.fish'
#source './aliases/drizzle.fish'
#source './aliases/fzf.fish'
#source './aliases/git.fish'
#source './aliases/init.fish'

#alias cc='clear'
