name: "Claude"
details: "light"
accent: "#ff6b35"
background: "#fefefe"
foreground: "#2d2d2d"
terminal_colors:
  normal:
    black: "#2d2d2d"
    red: "#e74c3c"
    green: "#27ae60"
    yellow: "#f39c12"
    blue: "#3498db"
    magenta: "#9b59b6"
    cyan: "#16a085"
    white: "#95a5a6"
  bright:
    black: "#34495e"
    red: "#ff6b35"
    green: "#2ecc71"
    yellow: "#f1c40f"
    blue: "#5dade2"
    magenta: "#af7ac5"
    cyan: "#48c9b0"
    white: "#ecf0f1"
