name: "Vercel"
details: "darker"
accent: "#ffffff"
background: "#000000"
foreground: "#ffffff"
terminal_colors:
  normal:
    black: "#000000"
    red: "#ff0080"
    green: "#00ff41"
    yellow: "#ffff00"
    blue: "#0070f3"
    magenta: "#ff0080"
    cyan: "#50e3c2"
    white: "#fafafa"
  bright:
    black: "#333333"
    red: "#ff3399"
    green: "#33ff66"
    yellow: "#ffff66"
    blue: "#3399ff"
    magenta: "#ff3399"
    cyan: "#66ffcc"
    white: "#ffffff"
