color_theme = "catppuccin_mocha"
theme_background = False
rounded_corners = True
graph_symbol = "braille"
shown_boxes = "cpu mem net proc"
update_ms = 1000
proc_sorting = "cpu lazy"
proc_tree = False
proc_gradient = True
cpu_graph_upper = "total"
cpu_graph_lower = "total"

