#!/usr/bin/env bash

export DOTFILES_ROOT="$HOME/.config/dotfiles"
export DOTFILES_CONFIG="$DOTFILES_ROOT/configs"
export DOTFILES_MODULES="$DOTFILES_ROOT/modules"
export DOTFILES_BIN="$DOTFILES_ROOT/bin"
export DOTFILES_UTILS="$DOTFILES_ROOT/utils"
export DOTFILES_LOGS="$DOTFILES_ROOT/logs"
export DOTFILES_ASSETS="$DOTFILES_ROOT/assets"
export DOTFILES_SCRIPTS="$DOTFILES_ROOT/scripts"

export SHEBANG='#!/usr/bin/env bash'

export DOTFILES_VERSION="0.0.97"

export DOTFILES_SHELL="${SHELL##*/}"
if [[ "$DOTFILES_SHELL" == "bash" ]]; then
    export DOTFILES_RC="$HOME/.bashrc"
elif [[ "$DOTFILES_SHELL" == "zsh" ]]; then
    export DOTFILES_RC="$HOME/.zshrc"
else
    export DOTFILES_RC="$HOME/.${DOTFILES_SHELL}rc"
fi

export DOTFILES_DEBUG="${DOTFILES_DEBUG:-0}"

export DOTFILES_LINKS_DB="$DOTFILES_UTILS/links.json"
export DOTFILES_ENV_DB="$DOTFILES_UTILS/env.json"

export DOTFILES_LOG_FILE="$DOTFILES_LOGS/dotfiles.log"
export DOTFILES_ERROR_LOG="$DOTFILES_LOGS/error.log"

[[ ! -f "$DOTFILES_LINKS_DB" ]] && echo '{}' > "$DOTFILES_LINKS_DB"
[[ ! -f "$DOTFILES_ENV_DB" ]] && echo '{}' > "$DOTFILES_ENV_DB"
