#!/usr/bin/env bash

function dotfiles_add_to_path() {
    if [[ -d "$DOTFILES_BIN" ]]; then
        export PATH="$DOTFILES_BIN:$PATH"
        echo.debug "Added $DOTFILES_BIN to PATH"
    fi
    
    [[ -d "$HOME/.local/bin" ]] && export PATH="$HOME/.local/bin:$PATH"
    [[ -d "$HOME/bin" ]] && export PATH="$HOME/bin:$PATH"
    [[ -d "/usr/local/go/bin" ]] && export PATH="/usr/local/go/bin:$PATH"
    [[ -d "$HOME/go/bin" ]] && export PATH="$HOME/go/bin:$PATH"
    [[ -d "$HOME/.cargo/bin" ]] && export PATH="$HOME/.cargo/bin:$PATH"
    [[ -d "$HOME/.npm-global/bin" ]] && export PATH="$HOME/.npm-global/bin:$PATH"
    
    export PATH=$(echo "$PATH" | tr ':' '\n' | awk '!seen[$0]++' | tr '\n' ':' | sed 's/:$//')
}

function dotfiles_setup_shell() {
    if [[ "$DOTFILES_SHELL" == "bash" ]]; then
        shopt -s histappend
        shopt -s checkwinsize
        shopt -s globstar 2>/dev/null
        shopt -s autocd 2>/dev/null
        shopt -s cdspell 2>/dev/null
        shopt -s dirspell 2>/dev/null
        shopt -s dotglob
        shopt -s extglob
        shopt -s nocaseglob
        
        if [[ -f /etc/bash_completion ]]; then
            source /etc/bash_completion
        elif [[ -f /usr/share/bash-completion/bash_completion ]]; then
            source /usr/share/bash-completion/bash_completion
        fi
        
    elif [[ "$DOTFILES_SHELL" == "zsh" ]]; then
        setopt AUTO_CD
        setopt AUTO_PUSHD
        setopt PUSHD_IGNORE_DUPS
        setopt PUSHD_SILENT
        setopt CORRECT
        setopt CORRECT_ALL
        setopt GLOB_COMPLETE
        setopt EXTENDED_GLOB
        setopt NO_CASE_GLOB
        setopt NUMERIC_GLOB_SORT
        setopt HIST_IGNORE_ALL_DUPS
        setopt HIST_SAVE_NO_DUPS
        setopt HIST_REDUCE_BLANKS
        setopt INC_APPEND_HISTORY
        setopt SHARE_HISTORY
        setopt HIST_VERIFY
        setopt INTERACTIVE_COMMENTS
        setopt COMPLETE_IN_WORD
        setopt ALWAYS_TO_END
        setopt PATH_DIRS
        setopt AUTO_MENU
        setopt AUTO_LIST
        setopt AUTO_PARAM_SLASH
        setopt EXTENDED_HISTORY
        setopt NO_BEEP
        
        autoload -Uz compinit && compinit -i
        autoload -Uz bashcompinit && bashcompinit
        
        zstyle ':completion:*' menu select
        zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|=*' 'l:|=* r:|=*'
        zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
        zstyle ':completion:*' rehash true
        zstyle ':completion:*' accept-exact '*(N)'
        zstyle ':completion:*' use-cache on
        zstyle ':completion:*' cache-path ~/.cache/zsh
        zstyle ':completion:*:descriptions' format '%U%B%d%b%u'
        zstyle ':completion:*:warnings' format '%BSorry, no matches for: %d%b'
    fi
}

function dotfiles_load_modules() {
    echo.debug "Loading modules..."
    
    safe_source_dir "$DOTFILES_MODULES/loaders" "*.sh" "module loaders"
    
    safe_source_dir "$DOTFILES_MODULES/enabled" "*.sh" "enabled modules"
    
    [[ -f "$DOTFILES_MODULES/aliases/loader" ]] && safe_source "$DOTFILES_MODULES/aliases/loader" "alias loader"
    [[ -f "$DOTFILES_MODULES/plugins/loader" ]] && safe_source "$DOTFILES_MODULES/plugins/loader" "plugin loader"
    [[ -f "$DOTFILES_MODULES/scripts/loader" ]] && safe_source "$DOTFILES_MODULES/scripts/loader" "script loader"
    
    safe_source_dir "$HOME/.config/dotfiles-local/modules" "*.sh" "local modules"
}

function dotfiles_load_configs() {
    safe_source_dir "$DOTFILES_CONFIG" "*.sh" "config files"
}

function dotfiles_setup_aliases() {
    alias ls='ls --color=auto'
    alias ll='ls -alF'
    alias la='ls -A'
    alias l='ls -CF'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
    
    alias ..='cd ..'
    alias ...='cd ../..'
    alias ....='cd ../../..'
    alias .....='cd ../../../..'
    
    alias md='mkdir -p'
    alias rd='rmdir'
    alias cls='clear'
    
    alias h='history'
    alias j='jobs -l'
    alias which='type -a'
    alias path='echo -e ${PATH//:/\\n}'
    
    alias now='date +"%T"'
    alias nowdate='date +"%Y-%m-%d"'
    
    alias vi='${EDITOR}'
    alias vim='${EDITOR}'
    alias svi='sudo ${EDITOR}'
    
    alias ports='netstat -tulanp'
    alias mount='mount | column -t'
    
    alias meminfo='free -m -l -t'
    alias psmem='ps auxf | sort -nr -k 4'
    alias pscpu='ps auxf | sort -nr -k 3'
    
    alias wget='wget -c'
    
    alias df='df -H'
    alias du='du -ch'
    
    alias top='htop'
}

function dotfiles_setup_prompt() {
    if [[ "$DOTFILES_SHELL" == "bash" ]]; then
        if [[ -f "$DOTFILES_MODULES/enabled/prompt-bash" ]]; then
            safe_source "$DOTFILES_MODULES/enabled/prompt-bash"
        else
            PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
        fi
        
    elif [[ "$DOTFILES_SHELL" == "zsh" ]]; then
        if [[ -f "$DOTFILES_MODULES/enabled/prompt-zsh" ]]; then
            safe_source "$DOTFILES_MODULES/enabled/prompt-zsh"
        else
            autoload -U colors && colors
            PS1="%{$fg[green]%}%n@%m%{$reset_color%}:%{$fg[blue]%}%~%{$reset_color%}$ "
        fi
    fi
}

function dotfiles_bootstrap() {
    ensure_dir "$DOTFILES_LOGS"
    ensure_dir "$DOTFILES_UTILS"
    ensure_dir "$DOTFILES_BIN"
    ensure_dir "$DOTFILES_MODULES/enabled"
    ensure_dir "$DOTFILES_MODULES/disabled"
    ensure_dir "$DOTFILES_CONFIG"
    ensure_dir "$DOTFILES_TEMPLATES"
    
    ensure_file "$DOTFILES_LINKS_DB" "{}"
    ensure_file "$DOTFILES_ENV_DB" "{}"
    ensure_file "$DOTFILES_STATE" '{"version":"'$DOTFILES_VERSION'","last_update":"'$(date -Iseconds)'"}'
    
    dotfiles_add_to_path
    dotfiles_setup_shell
    dotfiles_setup_aliases
    dotfiles_load_configs
    dotfiles_load_modules
    dotfiles_setup_prompt
    
    if command -v direnv &>/dev/null; then
        eval "$(direnv hook $DOTFILES_SHELL)"
    fi
    
    if [[ -f "$HOME/.fzf.$DOTFILES_SHELL" ]]; then
        source "$HOME/.fzf.$DOTFILES_SHELL"
    fi
    
    if [[ -f "$HOME/.config/dotfiles-local/init" ]]; then
        safe_source "$HOME/.config/dotfiles-local/init" "local customizations"
    fi
}
