// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelInstall():Promise<void>;

export function Catalog():Promise<Array<main.CatalogCategory>>;

export function CheckPresence(arg1:Array<string>):Promise<Record<string, boolean>>;

export function RunInstall(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function SystemInfo():Promise<main.SystemInfo>;
