// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelInstall() {
  return window['go']['main']['App']['CancelInstall']();
}

export function Catalog() {
  return window['go']['main']['App']['Catalog']();
}

export function CheckPresence(arg1) {
  return window['go']['main']['App']['CheckPresence'](arg1);
}

export function RunInstall(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunInstall'](arg1, arg2, arg3);
}

export function SystemInfo() {
  return window['go']['main']['App']['SystemInfo']();
}
