format = """
[](#1A1A1A)\
$username\
[](bg:#32CD32 fg:#1A1A1A)\
$directory\
[](fg:#32CD32 bg:#00FF7F)\
$git_branch\
$git_status\
[](fg:#00FF7F bg:#9AFF9A)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#9AFF9A bg:#00FA54)\
$docker_context\
[](fg:#00FA54 bg:#ADFF2F)\
$time\
[ ](fg:#ADFF2F)\
"""

add_newline = false

[username]
show_always = true
style_user = "bg:#1A1A1A bold green"
style_root = "bg:#1A1A1A bold green"
format = '[  $user ]($style)'
disabled = false

[directory]
style = "bg:#32CD32 bold black"
format = "[ 󰉋 $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:#9AFF9A black bold"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#00FA54 black bold"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#9AFF9A black bold"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#9AFF9A black bold"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#00FF7F black bold"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#00FF7F black bold"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#9AFF9A black bold"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#9AFF9A black bold"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#9AFF9A black bold"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#9AFF9A black bold"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#9AFF9A black bold"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#9AFF9A black bold"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#9AFF9A black bold"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#9AFF9A black bold"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#9AFF9A black bold"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#ADFF2F black bold"
format = '[ ☢️ $time ]($style)'

[character]
success_symbol = '[⟩⟩⟩](bold green)'
error_symbol = '[⟩⟩⟩](bold red)'
