name: "Arch Ricer"
details: "darker"
accent: "#1793d1"
background: "#0c0c0c"
foreground: "#ffffff"
terminal_colors:
  normal:
    black: "#0c0c0c"
    red: "#ff5555"
    green: "#55ff55"
    yellow: "#ffff55"
    blue: "#5555ff"
    magenta: "#ff55ff"
    cyan: "#55ffff"
    white: "#bbbbbb"
  bright:
    black: "#555555"
    red: "#ff5555"
    green: "#55ff55"
    yellow: "#ffff55"
    blue: "#5555ff"
    magenta: "#ff55ff"
    cyan: "#55ffff"
    white: "#ffffff"
