name: "Matrix"
details: "darker"
accent: "#00ff00"
background: "#000000"
foreground: "#00ff00"
terminal_colors:
  normal:
    black: "#000000"
    red: "#003300"
    green: "#00ff00"
    yellow: "#33ff33"
    blue: "#004400"
    magenta: "#006600"
    cyan: "#00cc00"
    white: "#00aa00"
  bright:
    black: "#002200"
    red: "#005500"
    green: "#33ff33"
    yellow: "#66ff66"
    blue: "#007700"
    magenta: "#009900"
    cyan: "#00ee00"
    white: "#ffffff"
