name: "T3 Chat"
details: "darker"
accent: "#a855f7"
background: "#0f0f23"
foreground: "#e2e8f0"
terminal_colors:
  normal:
    black: "#1e1e3f"
    red: "#f87171"
    green: "#4ade80"
    yellow: "#fbbf24"
    blue: "#60a5fa"
    magenta: "#a855f7"
    cyan: "#22d3ee"
    white: "#cbd5e1"
  bright:
    black: "#374151"
    red: "#fca5a5"
    green: "#86efac"
    yellow: "#fcd34d"
    blue: "#93c5fd"
    magenta: "#c084fc"
    cyan: "#67e8f9"
    white: "#f1f5f9"
