package main

import "testing"

func TestParseMonitorLine(t *testing.T) {
	cases := []struct {
		name    string
		line    string
		wantKey string
		wantOK  bool
	}{
		{
			name:    "physical keypress is captured",
			line:    "ydotoold virtual device\t2333:6666:e7fb73a9\tcapslock down",
			wantKey: "capslock",
			wantOK:  true,
		},
		{
			name: "keyd's virtual keyboard is the only keyboard source once the daemon grabs the device",
			line: keydVirtualDevice + "\t0fac:0ade:bea394c0\tesc down",

			wantKey: "esc",
			wantOK:  true,
		},
		{
			name:   "mouse buttons are ignored: the daemon does not grab pointers",
			line:   "UBEST zoom65 wireless Mouse\t1ea7:7777:0231b494\tleftmouse down",
			wantOK: false,
		},
		{
			name:   "scroll wheel is ignored",
			line:   "UBEST zoom65 wireless Mouse\t1ea7:7777:0231b494\tscrolldown down",
			wantOK: false,
		},
		{
			name:   "key release is ignored",
			line:   "UBEST zoom65 wireless\t1ea7:7777:f121f083\tcapslock up",
			wantOK: false,
		},
		{
			name:   "device announcements are ignored",
			line:   "device added: 1ea7:7777:f121f083 UBEST zoom65 wireless (/dev/input/event25)",
			wantOK: false,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got, ok := parseMonitorLine(tc.line)
			if ok != tc.wantOK {
				t.Fatalf("ok = %v, want %v", ok, tc.wantOK)
			}
			if ok && got.Key != tc.wantKey {
				t.Fatalf("key = %q, want %q", got.Key, tc.wantKey)
			}
		})
	}
}

func TestResolveCapturedKeyUndoesLiveRemap(t *testing.T) {
	reverse := map[string]string{"esc": "capslock", "left": "j"}

	cases := []struct {
		name         string
		in           KeydCapturedKey
		wantKey      string
		wantRemapped bool
	}{
		{
			name:         "post-remap esc resolves back to the capslock actually pressed",
			in:           KeydCapturedKey{Device: keydVirtualDevice, Key: "esc"},
			wantKey:      "capslock",
			wantRemapped: true,
		},
		{
			name:    "an unremapped key passes through untouched",
			in:      KeydCapturedKey{Device: keydVirtualDevice, Key: "f1"},
			wantKey: "f1",
		},
		{
			name:    "an ungrabbed physical device is already pre-remap",
			in:      KeydCapturedKey{Device: "ydotoold virtual device", Key: "esc"},
			wantKey: "esc",
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := resolveCapturedKey(tc.in, reverse)
			if got.Key != tc.wantKey {
				t.Errorf("key = %q, want %q", got.Key, tc.wantKey)
			}
			if got.Remapped != tc.wantRemapped {
				t.Errorf("remapped = %v, want %v", got.Remapped, tc.wantRemapped)
			}
			if got.Raw != tc.in.Key {
				t.Errorf("raw = %q, want %q", got.Raw, tc.in.Key)
			}
		})
	}
}

func TestEmittedKey(t *testing.T) {
	cases := map[string]string{
		"esc":                        "esc",
		"overload(control, esc)":     "esc",
		"timeout(esc, 200, control)": "esc",
		"layer(nav)":                 "",
		"macro(hello)":               "",
	}
	for action, want := range cases {
		if got := emittedKey(action); got != want {
			t.Errorf("emittedKey(%q) = %q, want %q", action, got, want)
		}
	}
}

func TestRenderParseRoundTrip(t *testing.T) {
	bindings := []KeydBinding{
		{Layer: "nav", Key: "h", Action: "left"},
		{Layer: "main", Key: "capslock", Action: "overload(control, esc)"},
		{Layer: "main", Key: "rightalt", Action: "layer(nav)"},
	}

	rendered := renderKeydConfig(bindings)
	if result := keydCheck(rendered); !result.OK {
		t.Fatalf("keyd rejected rendered config: %s\n%s", result.Output, rendered)
	}

	parsed := parseKeydConfig(rendered)
	if len(parsed) != len(bindings) {
		t.Fatalf("got %d bindings, want %d", len(parsed), len(bindings))
	}
	if parsed[0].Layer != keydMainLayer {
		t.Errorf("main layer should be rendered first, got %q", parsed[0].Layer)
	}

	want := map[string]KeydBinding{}
	for _, b := range bindings {
		want[b.Layer+"/"+b.Key] = b
	}
	for _, got := range parsed {
		expected, ok := want[got.Layer+"/"+got.Key]
		if !ok {
			t.Errorf("unexpected binding %+v", got)
			continue
		}
		if got.Action != expected.Action {
			t.Errorf("%s/%s action = %q, want %q", got.Layer, got.Key, got.Action, expected.Action)
		}
	}
}

func TestKeydCheckRejectsBadKey(t *testing.T) {
	result := keydCheck(renderKeydConfig([]KeydBinding{
		{Layer: "main", Key: "definitely_not_a_key", Action: "esc"},
	}))
	if result.OK {
		t.Fatal("expected keyd check to reject an unknown key name")
	}
}

func TestNormalizeConfigIgnoresFormatting(t *testing.T) {
	stored := "# Generated by dotfiles-studio.\n\n[main]\ncapslock = esc\n"
	applied := "[main]\n# Make CapsLock act as Escape everywhere.\ncapslock  =  esc\n"

	if normalizeConfig(stored) != normalizeConfig(applied) {
		t.Fatalf("configs should compare equal:\n%q\n%q", normalizeConfig(stored), normalizeConfig(applied))
	}
}

func TestSanitizeProfileName(t *testing.T) {
	if _, err := sanitizeProfileName("../../etc/passwd"); err == nil {
		t.Fatal("path traversal should be rejected")
	}
	if _, err := sanitizeProfileName(""); err == nil {
		t.Fatal("empty name should be rejected")
	}
	if got, err := sanitizeProfileName("gaming_v2"); err != nil || got != "gaming_v2" {
		t.Fatalf("got %q, %v", got, err)
	}
}
