background {
    monitor =
    color = rgba(16, 19, 23, 1.0)
}

general {
    disable_loading_bar = true
    hide_cursor = true
    grace = 2
}

input-field {
    monitor =
    size = 260, 48
    outline_thickness = 1
    dots_size = 0.25
    dots_spacing = 0.28
    outer_color = rgba(110, 231, 216, 0.65)
    inner_color = rgba(36, 43, 51, 0.94)
    font_color = rgba(215, 221, 232, 1.0)
    fade_on_empty = false
    placeholder_text = password
    check_color = rgba(242, 193, 78, 0.9)
    fail_color = rgba(255, 107, 122, 0.9)
    position = 0, -35
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    color = rgba(242, 193, 78, 1.0)
    font_size = 54
    font_family = Iosevka Nerd Font Propo
    position = 0, 80
    halign = center
    valign = center
}

label {
    monitor =
    text = locked
    color = rgba(143, 155, 168, 1.0)
    font_size = 14
    font_family = Iosevka Nerd Font Propo
    position = 0, 34
    halign = center
    valign = center
}
