-- Generated by nwg-displays on 2026-09-02 at 23:30:37. Do not edit manually.

hl.monitor({
    output = "HDMI-A-1",
    disabled = true
})
hl.monitor({
    output = "DP-2",
    mode = "3840x2160@144.05",
    position = "2560x0",
    scale = 1.0
})
