format = """
[](color_mauve)\
$os\
$username\
[](bg:color_blue fg:color_mauve)\
$directory\
[](fg:color_blue bg:color_teal)\
$git_branch\
$git_status\
[](fg:color_teal bg:color_green)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_green bg:color_surface1)\
$docker_context\
$conda\
[](fg:color_surface1 bg:color_base)\
$time\
[ ](fg:color_base)\
$line_break$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
color_text = '#cdd6f4'
color_base = '#1e1e2e'
color_surface0 = '#313244'
color_surface1 = '#45475a'
color_surface2 = '#585b70'
color_overlay0 = '#6c7086'
color_mauve = '#cba6f7'
color_blue = '#89b4fa'
color_teal = '#94e2d5'
color_green = '#a6e3a1'
color_yellow = '#f9e2af'
color_peach = '#fab387'
color_red = '#f38ba8'
color_pink = '#f5c2e7'

[os]
disabled = false
style = "bg:color_mauve fg:color_base"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:color_mauve fg:color_base"
style_root = "bg:color_mauve fg:color_base"
format = '[ $user ]($style)'

[directory]
style = "fg:color_base bg:color_blue"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_teal"
format = '[[ $symbol $branch ](fg:color_base bg:color_teal)]($style)'

[git_status]
style = "bg:color_teal"
format = '[[($all_status$ahead_behind )](fg:color_base bg:color_teal)]($style)'

[nodejs]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:color_base bg:color_green)]($style)'

[c]
symbol = " "
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:color_base bg:color_green)]($style)'

[rust]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:color_base bg:color_green)]($style)'

[golang]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:color_base bg:color_green)]($style)'

[php]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:color_base bg:color_green)]($style)'

[java]
symbol = " "
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:color_base bg:color_green)]($style)'

[kotlin]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:color_base bg:color_green)]($style)'

[haskell]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:color_base bg:color_green)]($style)'

[python]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol( $version) ](fg:color_base bg:color_green)]($style)'

[docker_context]
symbol = ""
style = "bg:color_surface1"
format = '[[ $symbol( $context) ](fg:color_teal bg:color_surface1)]($style)'

[conda]
style = "bg:color_surface1"
format = '[[ $symbol( $environment) ](fg:color_teal bg:color_surface1)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_base"
format = '[[  $time ](fg:color_text bg:color_base)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_mauve)'
vimcmd_replace_symbol = '[](bold fg:color_mauve)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
