// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/docs/*": {
    params: {
      "*": string;
    };
  };
  "/api/search": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/docs/*" | "/api/search";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "docs/page.tsx": {
    id: "docs/page";
    page: "/docs/*";
  };
  "docs/search.ts": {
    id: "docs/search";
    page: "/api/search";
  };
};