use std::fs;
use std::path::{Path, PathBuf};

use keybind_core::export::{export_profiles, import_bundle, Bundle};
use keybind_core::model::AppConfig;
use keybind_core::StructuredError;

pub fn checked_path(raw: &str) -> Result<PathBuf, StructuredError> {
    let path = PathBuf::from(raw);
    if !path.is_absolute() {
        return Err(StructuredError::new("BAD_PATH", "path must be absolute"));
    }
    if raw.contains("..") {
        return Err(StructuredError::new(
            "BAD_PATH",
            "path may not contain '..'",
        ));
    }
    let home = dirs::home_dir()
        .ok_or_else(|| StructuredError::new("NO_HOME", "cannot resolve home directory"))?;
    if !path.starts_with(&home) {
        return Err(StructuredError::new(
            "BAD_PATH",
            "exports and imports must stay inside your home directory",
        ));
    }
    Ok(path)
}

pub fn export_to(
    config: &AppConfig,
    profile_id: Option<&str>,
    dir: &str,
    include_hardware: bool,
) -> Result<String, StructuredError> {
    let dir = checked_path(dir)?;
    fs::create_dir_all(&dir)
        .map_err(|e| StructuredError::new("IO", format!("cannot create {}: {e}", dir.display())))?;

    let profiles: Vec<_> = match profile_id {
        Some(id) => config
            .profiles
            .iter()
            .filter(|p| p.id == id)
            .cloned()
            .collect(),
        None => config.profiles.clone(),
    };
    if profiles.is_empty() {
        return Err(StructuredError::new("NOT_FOUND", "profile not found"));
    }

    let toml = export_profiles(&profiles, include_hardware).map_err(StructuredError::from)?;
    let config_path = dir.join("config.toml");
    write_if_changed(&config_path, &toml)?;
    write_if_changed(&dir.join("install.sh"), INSTALL_SH)?;
    set_executable(&dir.join("install.sh"));
    Ok(config_path.to_string_lossy().into_owned())
}

pub fn import_from(path: &str) -> Result<Bundle, StructuredError> {
    let path = checked_path(path)?;
    let meta = fs::symlink_metadata(&path)
        .map_err(|e| StructuredError::new("IO", format!("cannot read {}: {e}", path.display())))?;
    if meta.file_type().is_symlink() {
        return Err(StructuredError::new(
            "BAD_PATH",
            "refusing to import through a symlink",
        ));
    }
    if meta.len() > 1024 * 1024 {
        return Err(StructuredError::new(
            "TOO_LARGE",
            "import file exceeds 1 MiB",
        ));
    }
    let raw = fs::read_to_string(&path)
        .map_err(|e| StructuredError::new("IO", format!("cannot read {}: {e}", path.display())))?;
    import_bundle(&raw).map_err(StructuredError::from)
}

fn write_if_changed(path: &Path, content: &str) -> Result<(), StructuredError> {
    if fs::read_to_string(path)
        .map(|c| c == content)
        .unwrap_or(false)
    {
        return Ok(());
    }
    fs::write(path, content)
        .map_err(|e| StructuredError::new("IO", format!("cannot write {}: {e}", path.display())))
}

fn set_executable(path: &Path) {
    use std::os::unix::fs::PermissionsExt;
    let _ = fs::set_permissions(path, fs::Permissions::from_mode(0o755));
}

const INSTALL_SH: &str = r#"#!/bin/sh
# Generated by Keybind Manager. Idempotent; never installs packages on its own.
set -eu

DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG="$DIR/config.toml"
MODE="${1:-}"

say() { printf '%s\n' "$*"; }

if [ ! -f "$CONFIG" ]; then
    say "error: $CONFIG not found"
    exit 1
fi

if [ -f /etc/os-release ]; then
    . /etc/os-release
else
    say "error: /etc/os-release not found; unsupported system"
    exit 1
fi

case "${ID:-} ${ID_LIKE:-}" in
    *arch*) FAMILY=arch ;;
    *debian*|*ubuntu*) FAMILY=debian ;;
    *) FAMILY=other ;;
esac

MISSING=0
if ! command -v keyd >/dev/null 2>&1; then
    MISSING=1
    say "keyd is not installed. Install it with:"
    case "$FAMILY" in
        arch) say "  sudo pacman -S keyd" ;;
        debian) say "  sudo apt install keyd   # or build from https://github.com/rvaiya/keyd" ;;
        *) say "  build from source: https://github.com/rvaiya/keyd" ;;
    esac
fi
if ! command -v keybind-manager >/dev/null 2>&1; then
    MISSING=1
    say "keybind-manager is not installed; see its installation docs."
fi

if [ "$MODE" = "--check" ]; then
    keybind-manager validate "$CONFIG"
    exit $?
fi

if [ "$MISSING" -eq 1 ]; then
    say "install the missing dependencies above, then re-run this script"
    exit 1
fi

keybind-manager validate "$CONFIG"

if [ "$MODE" != "--yes" ]; then
    printf 'Apply %s to this system? [y/N] ' "$CONFIG"
    read -r answer
    case "$answer" in
        y|Y|yes) ;;
        *) say "aborted"; exit 1 ;;
    esac
fi

keybind-manager apply "$CONFIG"
"#;
